# Generated by Django 5.2.16 on 2026-07-09 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Secteur pédagogique',
                'verbose_name_plural': 'Secteurs pédagogiques',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'école")),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code école')),
                ('type_ecole', models.CharField(choices=[('PUBLIQUE', 'Publique'), ('PRIVEE', 'Privée'), ('COMMUNAUTAIRE', 'Communautaire'), ('CONFESSIONNELLE', 'Confessionnelle')], default='PUBLIQUE', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('milieu', models.CharField(choices=[('URBAIN', 'Urbain'), ('RURAL', 'Rural')], default='URBAIN', max_length=10)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('directeur', models.ForeignKey(blank=True, limit_choices_to={'role': 'DIRECTEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecole_dirigee', to=settings.AUTH_USER_MODEL, verbose_name='Directeur responsable')),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecoles', to='schools.sector', verbose_name='Secteur pédagogique')),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['nom'],
            },
        ),
    ]
