# Generated by Django 5.2.16 on 2026-07-09 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConseillerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conseillers', to='schools.sector')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conseiller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche Conseiller pédagogique',
                'verbose_name_plural': 'Fiches Conseillers pédagogiques',
            },
        ),
    ]
