# Generated by Django 5.2.16 on 2026-07-14 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_conseillerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='directeur',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'DIRECTEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecole_dirigee', to=settings.AUTH_USER_MODEL, verbose_name='Directeur responsable'),
        ),
    ]
