# Generated by Django 5.2.16 on 2026-07-14 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circonscriptions', '0001_initial'),
        ('schools', '0004_school_circonscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='circonscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecoles', to='circonscriptions.circonscription'),
        ),
    ]
