# Generated by Django 5.2.16 on 2026-07-09 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_prise_fonction', models.DateField(blank=True, null=True, verbose_name='Date de prise de fonction')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'DIRECTEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='director_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche Directeur',
                'verbose_name_plural': 'Fiches Directeurs',
            },
        ),
    ]
