# Generated by Django 5.2.16 on 2026-07-10 11:29

import apps.users.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_directorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=apps.users.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression')], max_length=15)),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle concerné')),
                ('objet_id', models.CharField(max_length=50, verbose_name="ID de l'objet")),
                ('objet_repr', models.CharField(blank=True, max_length=255, verbose_name="Représentation de l'objet")),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journalisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'action",
                'verbose_name_plural': 'Journal des actions',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['modele', 'objet_id'], name='users_audit_modele_cb1f76_idx'), models.Index(fields=['-date_action'], name='users_audit_date_ac_bd5a50_idx')],
            },
        ),
    ]
