# Generated by Django 5.2.16 on 2026-07-10 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(verbose_name="Date d'expiration")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=10)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_paiement', models.CharField(blank=True, help_text='Réservé à la future intégration de paiement en ligne.', max_length=100)),
                ('notifie_expiration', models.BooleanField(default=False, help_text="Passe à True une fois la notification d'expiration proche envoyée.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chef', models.OneToOneField(limit_choices_to={'role': 'CHEF_IEPP'}, on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_fin'],
            },
        ),
    ]
