# Generated by Django 5.2.16 on 2026-07-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='statut',
            field=models.CharField(choices=[('ESSAI', "Période d'essai"), ('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=10),
        ),
    ]
