# Generated by Django 5.2.16 on 2026-07-09 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nom_parent', models.CharField(blank=True, max_length=150, verbose_name='Nom du parent/tuteur')),
                ('contact_parent', models.CharField(blank=True, max_length=30, verbose_name='Contact parent/tuteur')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='teachers.classe')),
                ('ecole', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='schools.school')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenoms'],
            },
        ),
    ]
