# Generated by Django 5.2.16 on 2026-07-10 11:29

import apps.users.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_parent',
            field=apps.users.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Contact parent/tuteur'),
        ),
    ]
