# Generated by Django 5.2.16 on 2026-07-09 17:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(choices=[('LECTURE', 'Lecture'), ('EXPRESSION_ECRITE', 'Expression écrite'), ('POESIE', 'Poésie'), ('ECRITURE', 'Écriture'), ('DICTEE', 'Dictée'), ('MATHEMATIQUES', 'Mathématiques'), ('EDHC', 'EDHC'), ('EPS', 'EPS'), ('CHANT', 'Chant'), ('SCIENCES', 'Sciences et technologie'), ('HISTOIRE_GEO', 'Histoire-Géographie')], max_length=25)),
                ('composition', models.CharField(choices=[('COMP1', 'Composition 1'), ('COMP2', 'Composition 2'), ('COMP3', 'Composition 3'), ('COMP_FINALE', 'Composition finale')], max_length=15)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('annee_scolaire', models.CharField(help_text='Format : 2025-2026', max_length=9)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='teachers.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['eleve', 'matiere', 'composition'],
                'unique_together': {('eleve', 'matiere', 'composition', 'annee_scolaire')},
            },
        ),
    ]
