# Generated by Django 5.2.16 on 2026-07-14 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circonscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la circonscription')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chef', models.OneToOneField(limit_choices_to={'role': 'CHEF_IEPP'}, on_delete=django.db.models.deletion.CASCADE, related_name='circonscription_dirigee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Circonscription',
                'verbose_name_plural': 'Circonscriptions',
            },
        ),
    ]
