# Generated by Django 5.2.16 on 2026-07-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circonscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circonscription',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='circonscriptions/logos/'),
        ),
    ]
