# Generated by Django 5.2.16 on 2026-07-09 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_conseillerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='authorizations/pieces_jointes/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=15)),
                ('commentaire_chef', models.TextField(blank=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_autorisation', to=settings.AUTH_USER_MODEL)),
                ('chef', models.ForeignKey(blank=True, help_text='Chef IEPP ayant pris la décision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_autorisation', to='schools.school')),
            ],
            options={
                'verbose_name': "Demande d'autorisation",
                'verbose_name_plural': "Demandes d'autorisation",
                'ordering': ['-date_creation'],
            },
        ),
    ]
